site_name: Juggler's rant
site_description: A bloggin site built with Material for Mkdocs.
site_url: https://www.gayathri.dev
# Repository
# repo_name: my-creative-hub/blog
# repo_url: https://github.com/my-creative-hub/blog

# Copyright
copyright: Copyright &copy; 2016 - 2025 Gayathri Ramakrishnan

theme:
  name: material
  custom_dir: overrides
  favicon: images/pencil-alt-solid.png
  language: en
  icon:
    logo: fontawesome/solid/pencil
  features:
    - content.code.annotate  
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.path    
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest 
    - toc.follow         
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode 
  font:
    text: Roboto
    code: Roboto Mono       

plugins:
  - search
  - blog:
      blog_dir: .
      blog_toc: true
      archive_date_format: MMMM yyyy
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md
      enabled: true 
  - git-committers:
      enabled: true
      repository: my-creative-hub/blog
      branch: main
      token: !ENV GH_BLOG_TOKEN
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  generator: true
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.    
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/g3ram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gayathri-ram/     

hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     normalize_issue_symbols: true
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true  

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Blog: 
    - index.md
  - System Design: 
    # - system-design/index.md - TODO
    - Load Balancing: 
      - Introduction: system-design/beginner/scalability/load-balancing.md
      - Specialized Types: system-design/beginner/scalability/specialized-load-balancing.md
      - Summary: system-design/beginner/scalability/load-balancing-summary.md
      - AWS Load Balancers: system-design/beginner/scalability/load-balancing-aws.md
  - Machine Learning:
    - Statistical Concepts: machine-learning/foundation/statistical_concepts_blog.md
    - Types:
      - Supervised Learning: 
        - machine-learning/models/003-logistic-regression.md
      # - machine-learning/models/004-linear-regression.md              
  - Quick Reference:
      - Pandas: machine-learning/libraries/001-pandas.md                


