site_name: My Docs
site_url: https://blog.gayathri.dev
theme:
  name: material
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode     