site_name: Juggler's rant
site_description: A bloggin site built with Material for Mkdocs.
site_url: https://blog.gayathri.dev
# Repository
repo_name: my-creative-hub/blog
repo_url: https://github.com/my-creative-hub/blog

# Copyright
copyright: Copyright &copy; 2016 - 2025 Gayathri Ramakrishnan

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs  
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest 
    - toc.follow         
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference 
  font:
    text: Roboto
    code: Roboto Mono       

plugins:
  - search
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      pagination_per_page: 5
      blog_toc: true
  - tags:
      tags_file: tags.md
  - git-committers:
      enabled: true
      repository: my-creative-hub/blog
      branch: main
      token: !ENV GH_BLOG_TOKEN
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/g3ram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gayathri-ram/     

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
