authors:
  juggler:
    name: Gayathri Ramakrishnan
    description: Developer
    avatar: https://cdn-2.coralnodes.com/coralnodes/uploads/2022/03/DSC_1103_scaled-jpg-100-subs-best.jpg
    url: https://www.gayathri.dev 
